### ISSUE TITLE
Синтаксис

### ISSUE THREAD

**Issue by Semenov-Alexander** [jehy/arduino-esp8266-mh-z19-serial#7]
Евгений, посмотрите пожалуйста последние 15 строк кода в ino. Кажется там несколько скобок потерялось.
И в секции if (ppm >= 1000) тоже

**Comment by jehy** [comment]
не, формально там всё окей, однострочные иф-элс это вполне стандартная штука. Другой вопрос, что в большинстве современных codestyle такое не любят :)
